# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not add newline character before prompt
add_newline = false

# Single-lined prompt
[line_break]
disabled = true

[character]
success_symbol = "[❯](green)"

